### ISSUE TITLE
모바일(768px 이하) 해상도 관련 버그

### ISSUE THREAD

**Issue by mu-hun** [Team-Railgun/Lev6-Layout#10]
현제 2가지 버그가 일어나고 있습니다.
- 카드가 왼쪽으로 쏠림
- 일정표와 footer가 겹침 : (이건 도데체 뭐가 문제인지 모르겠네요 ㅡㅡ;)

**Comment by mu-hun** [comment]
@HelloWorld017 제가 생각한 해결법 : 카드가 왼쪽으로 쏠리는 현상은 768px 이하 해상도에서만 three.js 카메라를 옆으로 돌리던가 

두번째 방법은 수고가 더 들것 같은 방법인데.. 카드 전체를 오른쪽으로 옮기면 됩니다.

**Comment by HelloWorld017** [comment]
으으으 둘다 손이 많이 가는 해결법인ㄷ....
일정표와 푸터 겹치는건 제가 css 손볼게요

**Comment by mu-hun** [comment]
프로젝트 중단함
