### ISSUE TITLE
나이스 API를 이용한 학교 인증

### ISSUE THREAD

**Issue by mu-hun** [Team-Railgun/Lev6-Layout#14]
학교 인증 페이지 관련 이슈를 여기에 게시합니다.

**Comment by mu-hun** [comment]
학교 인증 부분은 pyneis 모듈을 js로 포팅해서 클라이언트 부분에 돌아가게 하는건 어떤가요?
https://github.com/hallazzang/pyneis

**Comment by HelloWorld017** [comment]
https://github.com/Team-Railgun/Lev6-Layout/blob/master/js/search.js 에 이미 XHR 따놨습니다.
아무래도 CORS 때문에 서버가 필요한데...

**Comment by mu-hun** [comment]
서버는 heroku 써보는건 어떤가요?
 깃헙 페이지, heroku 둘다 동일한 커스텀 도메인 적용해서 쓰면 될거 같은데..

**Comment by mu-hun** [comment]
https://devcenter.heroku.com

**Comment by HelloWorld017** [comment]
헤로쿠 좋기는 한데 값이 조금 비싸서...

**Comment by mu-hun** [comment]
이건 백엔드 작업때 하는걸로..
