### ISSUE TITLE
각 학급카드를 선택시 첫교시에서 마지막 교시를 보여주기

### ISSUE THREAD

**Issue by mu-hun** [Team-Railgun/Lev6-Layout#2]
ASDF

**Comment by mu-hun** [comment]
~~팝업은 구세대것이여서~~ 걍 alt 방식으로 하던가 three.js 부분에서 처리하는것도 나쁘지는 않을 듯

**Comment by HelloWorld017** [comment]
아니면 학급카드를 확장시키는 방법도 좋을것 같네요

**Comment by mu-hun** [comment]
어떤 방식으로 학급카드를 확장시키는 건지 설명할 수 있을까요..?

학년 시간표에서 학급카드를 선택하면 three.js 처리로 1교시부터 좌르륵 나오는 건가요...

**Comment by HelloWorld017** [comment]
네네 그런 방식으로요

**Comment by mu-hun** [comment]
오호.. 👍 주말에 3D브랜치 작업 좀 합시다!

**Comment by mu-hun** [comment]
@HelloWorld017 학급카드 부분은 다 된것 같은데 이제 이슈 닫을까요?

**Comment by HelloWorld017** [comment]
상관없을듯 합니다

**Comment by mu-hun** [comment]
닫음
