### ISSUE TITLE
시간표 관리자 페이지 구현

### ISSUE THREAD

**Issue by mu-hun** [Team-Railgun/Lev6-Layout#4]

**Comment by mu-hun** [comment]
@HelloWorld017 관리자 레이아웃을 어떻게 할지 모르겠네요.. 논의 좀 해봅시다.

**Comment by HelloWorld017** [comment]
음 우선 관리자 기능 중에 뭐가 필요하죠?

**Comment by mu-hun** [comment]
가장 필요한 기능이 시간표 편집이고..

그 밖에는 하단의 [여러 소식들] 부분에서
-  공지사항
- 커스텀 html(페이스북이라던지..)

**Comment by mu-hun** [comment]
시간표 편집외에는 간단하게 입력 폼만 넣으면 끝인데, 문제는 시간표 편집 레이아웃이죠..

**Comment by HelloWorld017** [comment]
시간표 편집도 간단히 입력폼 (x요일 x교시) 만들고 x요일 선택하면 그날 수업 쫙 보여주고 교시 입력하면 그날 해당학년 다른반 교시 쫙 보여주면 될거 같은데

**Comment by mu-hun** [comment]
시간표 편집 이외의 관리 기능은 index.html 에 집어 넣읍시다.

헤더 옆쪽에 Edit 아이콘 넣는 방식으로 ㅇㅁㅇ

**Comment by mu-hun** [comment]
헉 아니다.. 그냥 인덱스 페이지하고 관리자 페이지 둘다 넣죠!

**Comment by HelloWorld017** [comment]
- 시간표 선택을 통해 변경 세부사항 확인하게 만들기
- 교시 선택 기능 만들기

**Comment by mu-hun** [comment]
시멘틱-ui에 내장된 font-awsome 아이콘 폰트가 ui.js를 수정해도 적용이 안되던데 해결법 아시나요..

**Comment by mu-hun** [comment]
닫음
